version: '3'

services:
  php-fpm:
    image: php:7.4-fpm-buster
    container_name: php-fpm
    volumes:
      - ./data:/var/www/html
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
    ports:
      - 9000:9000

  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - php-fpm
    ports:
      - 8888:8888
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

  research-wiki:
    build: ./
    container_name: research-wiki
    depends_on:
      - nginx
    volumes:
      - ./data:/var/www/html