# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 19 Nov 2020 11:58:37 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$2OxAY6XQ2TLSDMKTrTmgWOd4dXtRM5n6p0JH5CeQlYGliq8RTdWT2:Administrator:admin@research-wiki:admin,user
